In [ ]:
#CREATING ARRAYS IN NUMPY
#Array
#0-Dimensional Array
#1-Dimensional Array
#2-Dimensional Array
#3-Dimensional Array

In [12]:
#0-Dimensional Array
import numpy as np
a=np.array(10)
a

array(10)

In [14]:
#1-Dimensional Array
import numpy as np
b=np.array([10,20,30,40])
b

array([10, 20, 30, 40])

In [21]:
b[3]


np.int64(40)

In [16]:
#2-Dimensional Array
import numpy as np
p=np.array([[10,20,30],[50,60,70]])
p

array([[10, 20, 30],
       [50, 60, 70]])

In [17]:
p[0][2]

np.int64(30)

In [22]:
#3-Dimensional Array
import numpy as np
d=np.array([[[10,20,30],[30,40,50]],[[60,70,80],[90,100,110]]])
d


array([[[ 10,  20,  30],
        [ 30,  40,  50]],

       [[ 60,  70,  80],
        [ 90, 100, 110]]])

In [25]:
d[1][1]

array([ 90, 100, 110])

In [37]:
#asarray
import numpy as np
a=[10,20,30,40]
b=np.asarray(a,dtype=float,order='C')
b


array([10., 20., 30., 40.])

In [40]:
s=([10,20,30],[40,50,60])
v=np.asarray(s,dtype=float,order='C')#Here 'C' means row major order and 'F' means column major order
print(v)

[[10. 20. 30.]
 [40. 50. 60.]]


In [ ]:
#nditer means N-Dimensional Iterator. It is used to iterate over an array.
import numpy as np
s=([10,20,30],[40,50,60])
v=np.asarray(s,dtype=float,order='C')#here 'C' means row major order 
for i in np.nditer(v):
    print(i)

10.0
20.0
30.0
40.0
50.0
60.0


In [43]:
v=np.asarray(s,dtype=float,order='F')#here 'F' means column major order 
for i in np.nditer(v):
    print(i)

10.0
40.0
20.0
50.0
30.0
60.0


In [56]:
#frombuffer :It is used to create an array from a binary data source.
import numpy as np
a=b"welcome to python"
np.frombuffer(a,dtype='S1')#Here 'S1' means string of length 1

array([b'w', b'e', b'l', b'c', b'o', b'm', b'e', b' ', b't', b'o', b' ',
       b'p', b'y', b't', b'h', b'o', b'n'], dtype='|S1')

In [48]:
np.frombuffer(a,dtype='S1',count=7)#here  count=7 means it will take first 7 elements from the binary data source.

array([b'w', b'e', b'l', b'c', b'o', b'm', b'e'], dtype='|S1')

In [49]:
np.frombuffer(a,dtype='S1',offset=8)#here  offset=8 means it will take elements from the binary data source starting from index 8.

array([b't', b'o', b' ', b'p', b'y', b't', b'h', b'o', b'n'], dtype='|S1')

In [50]:
np.frombuffer(a,dtype='S1',count=7,offset=2)

array([b'l', b'c', b'o', b'm', b'e', b' ', b't'], dtype='|S1')

In [51]:
#fromiter means 1-Dimensional Iterator. It is used to iterate over an array.
a=[10,20,30,40]
np.fromiter(a,dtype=float,count=2)

array([10., 20.])

In [ ]:
np.fromiter(a,dtype='S1',count=2)#S1 is byte string.

array([b'1', b'2'], dtype='|S1')

In [ ]:
#INSILIZING ARRAYS IN NUMPY
#1.Zeros
import numpy as np
np.zeros(3,dtype=int)

array([0, 0, 0])

In [63]:
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
#2.full means it will create an array of given shape and type, filled with fill_value.
import numpy as np
np.full(3,4)

array([4, 4, 4])

In [ ]:
np.full([2,3,6],20)#here 2 means parameter 3 means rows and 6 means columns and 20 means fill_value.

array([[[20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20]],

       [[20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20]]])

In [ ]:
#random.rand
import numpy as np
np.random.rand(2,3,4)#here in random.rand i gives random values with 0 to 1

array([[[0.9385201 , 0.73950634, 0.57753246, 0.59120302],
        [0.49361602, 0.45683443, 0.84334645, 0.69043772],
        [0.44974009, 0.11756576, 0.24059856, 0.86758123]],

       [[0.69371578, 0.63533634, 0.29840519, 0.61569044],
        [0.16052327, 0.74318857, 0.42754658, 0.19981075],
        [0.51965427, 0.52910867, 0.1370973 , 0.01644001]]])

In [68]:
#ones
import numpy as np
np.ones([3,4,2],dtype=int)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [ ]:
#eye means all diagnoal gives 1
import numpy as np
np.eye(4)#

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [85]:
#Numerical Ranges
#1.arange means start,stop,and step
import numpy as np
a=np.arange(10,20,1,dtype=int)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
#reshape is used to make demensions from arange
a.reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])